# Generated by Django 5.1.7 on 2025-03-23 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador_energias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumo',
            name='energia_consumida',
        ),
        migrations.CreateModel(
            name='RegistroConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispositivo', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('consumo_electrico', models.FloatField()),
                ('hora', models.IntegerField()),
                ('duracion', models.IntegerField()),
                ('consumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='simulador_energias.consumo')),
            ],
        ),
    ]
