# Generated by Django 5.1.7 on 2025-05-23 21:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador_energias', '0002_remove_consumo_energia_consumida_registroconsumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroconsumo',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
