# Generated by Django 5.1.7 on 2025-05-23 22:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador_energias', '0003_alter_registroconsumo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroconsumo',
            name='registro_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
