# Generated by Django 5.1.7 on 2025-05-28 22:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulador_energias', '0005_consumo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
