# Generated by Django 5.1.7 on 2025-05-23 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0004_remove_dispositivo_hogar_dispositivo_partehogar'),
        ('usuarios', '0002_alter_usuario_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='hogar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='dispositivos.hogar'),
        ),
    ]
