# Generated by Django 5.1.6 on 2025-03-10 19:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hogar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rango_consumo_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rango_consumo_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('consumo_watts', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('encendido', 'Encendido'), ('apagado', 'Apagado')], default='apagado', max_length=10)),
                ('hogar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.hogar')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='dispositivos.tipodispositivo')),
            ],
        ),
    ]
