# Generated by Django 5.1.7 on 2025-03-11 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0002_partehogar'),
    ]

    operations = [
        migrations.AddField(
            model_name='partehogar',
            name='hogar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='partes', to='dispositivos.hogar'),
        ),
    ]
