# Generated by Django 5.1.7 on 2025-03-16 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispositivos', '0003_partehogar_hogar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositivo',
            name='hogar',
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='partehogar',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dispositivos.partehogar'),
            preserve_default=False,
        ),
    ]
